### ISSUE TITLE
Busqueda de fechas posibles 

### ISSUE THREAD

**Issue by jhq1002** [dgs1016/Practica1-Software#1]
Discusión sobre la fecha que mejor nos viene a todos para hacer el viaje.

**Comment by Psm1015** [comment]
Yo puedo todo el mes de julio.

**Comment by jhq1002** [comment]
Yo solo puedo la segunda quincena de julio, pero me vendria mejor en agosto.

**Comment by jmm1053** [comment]
Estoy disponible todo julio.

**Comment by dgs1016** [comment]
Yo en agosto imposible. Si todos podemos la segunda quincena de julio pues vamos en esas fechas.

**Comment by Psm1015** [comment]
¿Cerramos fechas del 20 de julio al 30 de julio?
