### ISSUE TITLE
Búsqueda de actividades y excursiones.

### ISSUE THREAD

**Issue by Psm1015** [dgs1016/Practica1-Software#10]
Buscar diferentes actividades o excursiones que se puedan realizar en los países que vamos a visitar.

**Comment by dgs1016** [comment]
¿Te has informado de cosas para hacer en los países?

**Comment by Psm1015** [comment]
Cerca de Praga hay zonas para hacer kayak a 20 minutos en autobús.

**Comment by jhq1002** [comment]
¡Me parece genial!

**Comment by jmm1053** [comment]
Diego no le gustará mucho, no nada muy bien
