### ISSUE TITLE
Cerrar reserva vuelos

### ISSUE THREAD

**Issue by jhq1002** [dgs1016/Practica1-Software#15]
Cierre final de la reserva de los tickets de los vuelos.

**Comment by jhq1002** [comment]
¿Reservo ya los vuelos o quereis seguir mirando alguna alternativa más?

**Comment by dgs1016** [comment]
Si, contra más tardemos más caros van a ser.

**Comment by Psm1015** [comment]
Si tienen buen precio cómpralos ya

**Comment by jmm1053** [comment]
Cuanto antes mejor.
