### ISSUE TITLE
Equipaje

### ISSUE THREAD

**Issue by jhq1002** [dgs1016/Practica1-Software#18]
Lista de equipaje necesario para el viaje.

**Comment by dgs1016** [comment]
Juan, me tienes que decir con que compañía has cerrado los vuelos para mirar sus requerimientos.

**Comment by jhq1002** [comment]
Hemos cogido todo con AirEuropa.

**Comment by Psm1015** [comment]
Recordad llevar bañador.

**Comment by dgs1016** [comment]
Perfecto. Por lo que he visto es una de las compañías que menos exige a sus pasajeros. Deja llevar una maleta de cabina sin facturar y además hay una oferta de 2*1en facturación. Recordad no llevar líquidos con un contenido superior a 100ml.

**Comment by jmm1053** [comment]
Sabéis si dejan volar a mascotas, para que Freya no se quede aquí y pueda venir con nosotros.
