### ISSUE TITLE
Contrato de actividades y excursiones.

### ISSUE THREAD

**Issue by jmm1053** [dgs1016/Practica1-Software#19]
Queremos realizar al menos tres actividades y contratarlas para que queden así reservadas

**Comment by jhq1002** [comment]
Hay una ruta muy chula para hacer por el casco antiguo de Budapest.

**Comment by dgs1016** [comment]
Contrataría un guía porque si no vamos a estar muy perdidos y vamos a tardar mucho más en ver las ciudades.

**Comment by jhq1002** [comment]
Vale ahora lo miro.

**Comment by jmm1053** [comment]
Yo preferiría algo más movido, estilo una ruta en buggy

**Comment by Psm1015** [comment]
La ruta en buggy salía bien de precio, reservadla.

**Comment by dgs1016** [comment]
En Hungría, podríamos visitar las termas. ¡No olvidéis el bañador!

**Comment by jhq1002** [comment]
Todo ya está contratado, los kayaks, los buggys y las termas.
