### ISSUE TITLE
Gastos estimados.

### ISSUE THREAD

**Issue by Psm1015** [dgs1016/Practica1-Software#20]
Estimar el número de gastos una vez que tengamos todas las reservas hechas.

**Comment by jhq1002** [comment]
Acabo de hacer los cálculos, teniendo en cuenta todas las visitas que vamos ha hacer y las reservas saldría a unos 800€ los 10 días.

**Comment by jmm1053** [comment]
Por persona entiendo.

**Comment by Psm1015** [comment]
Vale, me parece un buen precio.

**Comment by dgs1016** [comment]
Buen precio.
