### ISSUE TITLE
Aeropuertos más convenientes para realizar el primer vuelo.

### ISSUE THREAD

**Issue by jmm1053** [dgs1016/Practica1-Software#3]
No todos vivimos en la misma ciudad, por lo que debemos buscar el aeropuerto que mejor venga a todos para realizar el primer vuelo.

**Comment by jhq1002** [comment]
Yo creo que lo mejor sería salir todos desde Madrid.

**Comment by dgs1016** [comment]
Yo también creo que es lo más cómodo y desde donde salen mas vuelos a diferentes destinos.

**Comment by Psm1015** [comment]
Bien, por localización es accesible para todos.
