### ISSUE TITLE
Itinerario a seguir por Europa.

### ISSUE THREAD

**Issue by jmm1053** [dgs1016/Practica1-Software#4]
Queremos visitar Centroeuropa, pero debemos de trazar un itinerario a seguir por los países que queramos visitar para llevar un orden y aprovechar el viaje al máximo.

**Comment by jmm1053** [comment]
La  idea principal sería salir de Rep. Checa - Hungría- Bosnia - Serbia y Grecia

**Comment by jhq1002** [comment]
¿En republica checa prefereis ir a Praga o a Pilsen?

**Comment by Psm1015** [comment]
Yo iría a Praga.
Del resto de países visitaría Budapest, Sarajevo, Belgrado y Atenas.

**Comment by dgs1016** [comment]
Yo iría a las principales ciudades de esos países.
