### ISSUE TITLE
Búsqueda de los vuelos de ida y vuelta

### ISSUE THREAD

**Issue by Psm1015** [dgs1016/Practica1-Software#5]
Buscar un vuelo rentable y que cuadre con las fechas de ida y vuelta del viaje.

**Comment by Psm1015** [comment]
Hay vuelos a Praga en julio desde 30 euros si los cogemos con antelación.

**Comment by jhq1002** [comment]
Yo los cogería ya.

**Comment by dgs1016** [comment]
Cuanto antes los cojamos, más barato nos sale.

**Comment by jmm1053** [comment]
Encima no hay que hacer escala.
