### ISSUE TITLE
Preparar aplicaciones de traducción.

### ISSUE THREAD

**Issue by jhq1002** [dgs1016/Practica1-Software#6]
Búsqueda de un par de aplicaciones de traducción.

**Comment by Psm1015** [comment]
¿Has encontrado ya alguna aplicación fiable para todos los idiomas?

**Comment by dgs1016** [comment]
Utilizaría el traductor de google y el traductor de cambridge

**Comment by dgs1016** [comment]
Así que Juan y Pablo, miradlo para tenerlo preparado.

**Comment by jhq1002** [comment]
Vale, ahora me los instalo

**Comment by jmm1053** [comment]
Unos amigos llevaron esas app y no tuvieron problema
