### ISSUE TITLE
Requerimientos y documentación

### ISSUE THREAD

**Issue by Psm1015** [dgs1016/Practica1-Software#8]
Buscar que documentos son necesarios en cada país y búsqueda de un seguro de viajes adecuado.

**Comment by dgs1016** [comment]
¿Te has informado sobre qué documentación es necesaria para poder ir?

**Comment by Psm1015** [comment]
Sí, solamente necesitamos el DNI y para algunos países el pasaporte. Aseguraros de que tenéis los dos en vigencia para esas fechas.

**Comment by jhq1002** [comment]
Yo tengo que sacarme el pasaporte.

**Comment by jmm1053** [comment]
Yo tengo ya todo ya.
