### ISSUE TITLE
Preparar aplicaciones de cambio de moneda

### ISSUE THREAD

**Issue by jhq1002** [dgs1016/Practica1-Software#9]
Elección de las aplicaciones para el cambio de moneda.

**Comment by jhq1002** [comment]
Por lo que tengo entendido las mejores aplicaciones de cambio de moneda son revolut y wise, si sabeis alguna más sería perfecto.

**Comment by dgs1016** [comment]
He oído hablar bien de revolut. La aplicación de wise no la conocía.

**Comment by Psm1015** [comment]
Podemos descargar las dos por si acaso una de las dos falla.

**Comment by jmm1053** [comment]
Yo llevaré en efectivo ya que muchos establecimientos en Bosnia no aceptan tarjetas.
